### ISSUE TITLE
Project error

### ISSUE THREAD

**Issue by Ahrovan** [IndeemaSoftware/qtsimplescada#1]
Hi
I installed QSimpleScada with qpm just run as admin and paste qpm install com.indeema.QSimpleScada:

C:\Users\User>qpm install com.indeema.QSimpleScada
INFO: Package com.indeema.qsimplescada has a different license (MIT) than it's dependant (NONE).
Installing com.indeema.qsimplescada@0.5.0

C:\Users\User>

, but in QSimpleScadaSample (cloned https://github.com/IndeemaSoftware/QSimpleScadaSample) QT project, say:

 error: QScadaBoard/qscadaboard.h: No such file or directory

please help me for solve this problem.
thanks

**Comment by vshevchyk** [comment]
Hello,

Please be sure that package was installed correctly and you have this kind of hierarchy
![screen shot 2018-12-20 at 12 47 25 pm](https://user-images.githubusercontent.com/2978800/50280590-96307480-0455-11e9-833b-21345cf1ecf3.png)

**Comment by Ahrovan** [comment]
solved.
