### ISSUE TITLE
Save Program has unexpectedly finished

### ISSUE THREAD

**Issue by Ahrovan** [IndeemaSoftware/qtsimplescada#2]
Hi, when I want to save program, QSimpleScadaSample.exe crashed.
```
setEditable
initConnectedDevices
setEditable
The program has unexpectedly finished.
C:\Users\Design\QSimpleScadaSample-master\debug\QSimpleScadaSample.exe crashed.
```

**Comment by vshevchyk** [comment]
I reproduced this issues. I should investigate the reason.

**Comment by vshevchyk** [comment]
Please try now.

**Comment by Ahrovan** [comment]
https://github.com/IndeemaSoftware/QSimpleScada/blob/476ca7e386c7af5f5f8b2541d9806c4a042d00bf/QScadaBoard/qscadaboard.cpp#L244
![image](https://user-images.githubusercontent.com/5772832/50376271-23272980-0620-11e9-994b-632a64d8210c.png)

problem started from [#L244](https://github.com/IndeemaSoftware/QSimpleScada/blob/476ca7e386c7af5f5f8b2541d9806c4a042d00bf/QScadaBoard/qscadaboard.cpp#L244)

**Comment by Ahrovan** [comment]
@vshevchyk  Have an idea about the problem?

**Comment by vshevchyk** [comment]
!ScadaBoard object was not initialized correctly. Please check if your central widget is promoted correctly.

![screen shot 2018-12-24 at 11 27 34 am](https://user-images.githubusercontent.com/2978800/50395824-f170a880-076e-11e9-9804-8e99c7a1220c.png)

**Comment by Ahrovan** [comment]
![image](https://user-images.githubusercontent.com/5772832/50396131-19ff9f00-077d-11e9-9e8e-a5b54a0bb592.png)
Similar to yours

**Comment by Ahrovan** [comment]
commented "mBoard->setEditable(true);" in:
```
void QScadaBoardController::initConnectedDevices(const QList<QScadaBoardInfo *> list)
{
    qDebug() << __FUNCTION__;
    for (QScadaBoardInfo *boardInfo : list) {
        if (boardInfo != nullptr) {
//            mBoard->setEditable(true);
            for (QScadaObjectInfo *info : boardInfo->objectList()) {
                QScadaObjectInfo *lInfo = new QScadaObjectInfo(info);
                mBoard->createNewObject(lInfo);
            }
        }
    }
    mBoard->update();
}
```
 and see:
```
setEditable
initConnectedDevices
QObject::connect: Cannot connect QScadaObject::objectDoubleClicked(QScadaObject*) to (null)::objectDoubleClicked(QScadaObject*)
QObject::connect: Cannot connect QScadaObject::objectSelected(int) to (null)::newObjectSelected(int)
QObject::connect: Cannot connect QScadaObject::objectMove(int,int) to (null)::objectMove(int,int)
QObject::connect: Cannot connect QScadaObject::objectResize(int,int) to (null)::objectResize(int,int)
setGeometry: Unable to set geometry 100x100+100+100 on QWidgetWindow/'QScadaObjectClassWindow'. Resulting geometry:  148x100+100+100 (frame: 9, 38, 9, 9, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215).
The program has unexpectedly finished.
```
ok, object was not initialized correctly

**Comment by vshevchyk** [comment]
I see. 
Saving and opening was wrongly implemented in this sample. I will need more time to fix that.

I'll let you know when it's fixed. Thanks.

**Comment by vshevchyk** [comment]
It was fixed.
